### ISSUE TITLE
Support for OPTIONS method

### ISSUE THREAD

**Issue by Ryhon0** [0Supa/uploader#2]
I'm developing a web based app and I'm using this service as the default file uploading service. Everything works fine if I make a simple XHR or fetch request to upload a file, but when I connect a upload progress listener, the browser no longer considers the request simple and makes a preflight request, which fails because the server treats all HTTP methods the same and expects form data on the preflight request, returning 500.

**Comment by 0Supa** [comment]
`OPTIONS` requests are now appropriately handled.
