### ISSUE TITLE
Backend

### ISSUE THREAD

**Issue by lucas19961** [0Supa/uploader#6]
Hey.

How does the backend work? 

What i need to run this ?

**Comment by 0Supa** [comment]
Unfortunately, the backend's source isn't disclosed, as it is closely tied to our internal infrastructure. If you want to selfhost this you'd have to modify the frontend to make it work alongside your backend. I recommend you looking into [file-uploader-crystal](https://codeberg.org/Fijxu/file-uploader-crystal) which has a similar structure to this service.
